apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: canary-app-dr
  namespace: deploy-lab
spec:
  host: canary-app-svc.deploy-lab.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v1
    labels: { version: v1 }
  - name: v2
    labels: { version: v2 }