apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
  namespace: deploy-lab
  labels:
    app: app-bluegreen
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-bluegreen
      version: blue
  template:
    metadata:
      labels:
        app: app-bluegreen
        version: blue
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        env:
        - name: APP_VERSION
          value: "blue"
        ports:
        - containerPort: 80