apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
  namespace: deploy-lab
  labels:
    app: app-bluegreen
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-bluegreen
      version: green
  template:
    metadata:
      labels:
        app: app-bluegreen
        version: green
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        env:
        - name: APP_VERSION
          value: "green"
        ports:
        - containerPort: 80