apiVersion: v1
kind: Service
metadata:
  name: app-bluegreen-svc
  namespace: deploy-lab
spec:
  type: ClusterIP
  selector:
    app: app-bluegreen
    version: green    # ðŸ”¹ start with blue
  ports:
  - port: 80
    targetPort: 80